[package]
name = "cw20-token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = "1.0.0"
cw20 = "0.13.2"
cw20-base = { version = "0.13.2", features = ["library"] }
